services:
  - type: pserv
    name: temporal-history
    autoDeploy: false
    plan: Standard
    env: docker
    dockerfilePath: ./temporal/server/Dockerfile
    dockerContext: ./temporal
    envVars:
    - key: STATSD_ENDPOINT
      fromService:
        name: temporal-datadog-agent
        type: pserv
        property: hostport
    - key: SERVICES
      value: history
    - fromGroup: dynamic-config
    - fromGroup: db-vars
    - fromGroup: visibility-db-vars
  - type: pserv
    autoDeploy: false
    name: temporal-frontend
    env: docker
    dockerfilePath: ./temporal/server/Dockerfile
    dockerContext: ./temporal
    envVars:
    - key: STATSD_ENDPOINT
      fromService:
        name: temporal-datadog-agent
        type: pserv
        property: hostport
    - key: SERVICES
      value: frontend
    - fromGroup: dynamic-config
    - fromGroup: db-vars
    - fromGroup: visibility-db-vars
  - type: pserv
    autoDeploy: false
    name: temporal-matching
    env: docker
    dockerfilePath: ./temporal/server/Dockerfile
    dockerContext: ./temporal
    envVars:
    - key: STATSD_ENDPOINT
      fromService:
        name: temporal-datadog-agent
        type: pserv
        property: hostport
    - key: SERVICES
      value: matching
    - fromGroup: dynamic-config
    - fromGroup: db-vars
    - fromGroup: visibility-db-vars
  - type: pserv
    autoDeploy: false
    name: temporal-srv-worker
    env: docker
    dockerfilePath: ./temporal/server/Dockerfile
    dockerContext: ./temporal
    envVars:
    - key: STATSD_ENDPOINT
      fromService:
        name: temporal-datadog-agent
        type: pserv
        property: hostport
    - key: PUBLIC_FRONTEND_ADDRESS
      fromService:
        name: temporal-frontend
        type: pserv
        property: hostport
    - key: SERVICES
      value: worker
    - fromGroup: dynamic-config
    - fromGroup: db-vars
    - fromGroup: visibility-db-vars
  - type: pserv
    autoDeploy: false
    name: temporal-datadog-agent
    env: docker
    dockerfilePath: ./datadog-agent/Dockerfile
    dockerContext: ./datadog-agent
    envVars:
    - key: DD_API_KEY
      sync: false
  - type: web
    autoDeploy: false
    name: temporal-ui
    env: docker
    dockerfilePath: ./temporal/ui/Dockerfile
    dockerContext: ./temporal
    envVars:
    - key: TEMPORAL_GRPC_ENDPOINT
      fromService:
        name: temporal-frontend
        type: pserv
        property: hostport
    - fromGroup: dynamic-config
  - type: worker
    autoDeploy: false
    name: temporal-admin-tools
    env: docker
    dockerfilePath: ./temporal/admin-tools/Dockerfile
    dockerContext: ./temporal/admin-tools
    envVars:
    - fromGroup: dynamic-config
    - fromGroup: db-vars
    - fromGroup: visibility-db-vars

envVarGroups:
- name: dynamic-config
  envVars:
  - key: TEMPORAL_CONFIG_PATH
    value: /etc/temporal/dynamicconfig.yaml
  - key: DYNAMIC_CONFIG_FILE_PATH
    value: /etc/temporal/dynamicconfig.yaml
- name: db-vars
  envVars:
    - key: DBNAME
      fromDatabase:
        name: temporal
        property: database
    - key: DB_PORT
      fromDatabase:
        name: temporal
        property: port
    - key: POSTGRES_USER
      fromDatabase:
        name: temporal
        property: user
    - key: POSTGRES_PWD
      fromDatabase:
        name: temporal
        property: password
    - key: POSTGRES_SEEDS
      fromDatabase:
        name: temporal
        property: host
- name: visibility-db-vars
  envVars:
    - key: VISIBILITY_DBNAME
      fromDatabase:
        name: temporalvisibility
        property: database
    - key: VISIBILITY_DB_PORT
      fromDatabase:
        name: temporalvisibility
        property: port
    - key: VISIBILITY_POSTGRES_USER
      fromDatabase:
        name: temporalvisibility
        property: user
    - key: VISIBILITY_POSTGRES_PWD
      fromDatabase:
        name: temporalvisibility
        property: password
    - key: VISIBILITY_POSTGRES_SEEDS
      fromDatabase:
        name: temporalvisibility
        property: host

databases:
  - name: temporal
    databaseName: temporal
    user: temporal
    plan: standard
  - name: temporalvisibility
    databaseName: temporalvisibility
    user: temporalvisibility
    plan: standard
